#!/usr/bin/env bash

##############################################################################
##
##  apkfly start up script for UN*X
##
##############################################################################

APP_HOME="`pwd -P`"
apkflyF=$APP_HOME/apkfly.sh
apkflyPy=$apkflyF/apkfly.py

# 1、判断一下python环境是否是2.x版本
pVersion=`python -c 'import sys; print(sys.version_info.major)'`
pVersionInt=`echo $pVersion| awk '{print int($0)}'`
if [ $pVersionInt -lt 3 ] ; then
  #echo 'python version 2.x'

  # 2、判断apkfly.sh仓库是否已下载，如没下载则clone，如已下载则pull
  if [ -d $apkflyF ];then
    # 更新仓库
    echo "apkfly.sh仓库存在，现在更新仓库"
    cd $apkflyF
    git pull
    cd .. # 把目录切回workspace
  else
    # clone仓库
    echo "apkfly.sh仓库不存在，现在clone仓库"
    git clone 'git@code.gome.inc:mobile-android-admin/apkfly.sh.git'
  fi

  echo -e "************************ 准备工作完成 ************************\n"

  # 3、执行apkfly.sh仓库中的python版脚本
  python $apkflyPy $@
else
  echo 'python version must 2.x'
fi





